name: TCentury
version: 0.1.1
author: Felantry
main: com.felantry.tcentury.TCenturyPlugin
api-version: 1.21
commands:
  tcentury:
    description: Команда для управления веками
    usage: /tcentury
permissions:
  tcentury.use:
    description: Разрешение на использование команд плагина
    default: true