name: TCentury
version: 0.3.0
author: Felantry
main: com.felantry.tcentury.TCenturyPlugin
api-version: 1.21
commands:
  tcentury:
    description: Основная команда плагина.
    usage: /tcentury
permissions:
  tcentury.reload:
    description: Разрешение на перезагрузку конфигурации.
    default: op